from tmux_launcher import Options


def get_opt():
	opt = Options()
	opt.set(
					R1_once_every = 16,                            
		               batch_size = 1,                             
		                    beta1 = 0.0,                           
		                    beta2 = 0.99,                          
		          checkpoints_dir = "./checkpoints/",                
		                crop_size = 512,                           	
		                 dataroot = ".",                             	
		             dataset_mode = "imagefolder",                   
		              display_env = "main",                          
		             display_freq = 1600,                          
		            display_ncols = 2,                             
		             display_port = 2004,                          
		              #easy_label =                               
		          evaluation_freq = 50000,                         
		       evaluation_metrics = "simple_swapping",               	
		           global_code_ch = 2048,                          
		    input_structure_image = "./testphotos/ffhq512/52.png",   	
		      input_texture_image = "./testphotos/ffhq512/137.png",  	
		                  isTrain = False,                         	
		               lambda_GAN = 1.0,                           
		                lambda_L1 = 1.0,                           
		          lambda_PatchGAN = 1.0,                           
		                lambda_R1 = 10.0,                          
		          lambda_patch_R1 = 1.0,                           
		                load_size = 512,                           	
		                       lr = 0.002,                         
		            max_num_tiles = 8,                             
		                    model = "swapping_autoencoder",          
		                 nThreads = 8,                             
		                     name = "ffhq512_pretrained",            	
		                     netD = "StyleGAN2",                     
		      netD_scale_capacity = 1.0,                           
		                     netE = "StyleGAN2Resnet",               
		        netE_nc_steepness = 2.0,                           
		 netE_num_downsampling_gl = 2,                             
		 netE_num_downsampling_sp = 4,                             
		      netE_scale_capacity = 1.0,                           
		                     netG = "StyleGAN2Resnet",               
		netG_num_base_resnet_layers = 2,                             
		           netG_resnet_ch = 256,                           
		      netG_scale_capacity = 1.0,                           
		           netG_use_noise = True,                          
		                netPatchD = "StyleGAN2",                     
		         netPatchD_max_nc = 384,                           
		 netPatchD_scale_capacity = 4.0,                           
		                  no_flip = False,                         
		                  no_html = True,                          
		              num_classes = 0,                             
		                 num_gpus = 1,                             
		                optimizer = "swapping_autoencoder",          
		          patch_max_scale = 0.25,                          
		          patch_min_scale = 0.125,                         
		          patch_num_crops = 8,                             
		patch_random_transformation = False,                         
		               patch_size = 128,                           
		    patch_use_aggregation = True,                          
		                    phase = "train",                         
		               preprocess = "scale_shortside",               	
		  preprocess_crop_padding = None,                          
		               print_freq = 480,                           
		               result_dir = "./results/",                    	
		              resume_iter = "latest",                        
		                save_freq = 50000,                         
		          shuffle_dataset = None,                          
		          spatial_code_ch = 8,                                   
		       texture_mix_alphas = [1.0],                         
		              total_nimgs = 25000000,                      
		            use_antialias = True                          
	)
	return opt